{{- if and .Values.blobStore.enabled (eq .Values.blobStore.type "s3") (not .Values.blobStore.s3.existingSecret) -}}
{{- if or .Values.blobStore.s3.accessKey .Values.blobStore.s3.secretKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "depot.s3SecretName" . }}
  labels:
    {{- include "depot.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.blobStore.s3.accessKey | quote }}
  secret-key: {{ .Values.blobStore.s3.secretKey | quote }}
{{- end -}}
{{- end -}}
