// SPDX-FileCopyrightText: 2026 Artifact Depot Contributors
//
// SPDX-License-Identifier: Apache-2.0

//! Dynamic middleware that reads settings per-request via `AppState.settings`.
//!
//! These replace the static layers that were previously baked into the router
//! at build time, allowing settings changes via the API to take effect without
//! a server restart.

use std::pin::Pin;
use std::task::{Context, Poll};

use crate::server::config::CorsConfig;
use crate::server::infra::state::AppState;
use axum::extract::State;
use axum::http::{header, HeaderValue, Method, StatusCode};
use axum::middleware;
use axum::response::{IntoResponse, Response};
use tracing::Instrument;

/// Unique identifier attached to every HTTP request.
///
/// Generated by [`request_id_middleware`] (or extracted from the incoming
/// `x-request-id` header) and made available to downstream layers via
/// request extensions.
#[derive(Clone, Debug)]
pub struct RequestId(pub String);

/// Assigns a request ID to every inbound request.
///
/// If the client sends an `x-request-id` header the value is reused;
/// otherwise a new UUID v4 is generated.  The ID is inserted into request
/// extensions and echoed back on the response.
pub async fn request_id_middleware(
    mut req: axum::http::Request<axum::body::Body>,
    next: middleware::Next,
) -> Response {
    let id = req
        .headers()
        .get("x-request-id")
        .and_then(|v| v.to_str().ok())
        .map(String::from)
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

    req.extensions_mut().insert(RequestId(id.clone()));

    let mut resp = next.run(req).await;
    if let Ok(val) = HeaderValue::from_str(&id) {
        resp.headers_mut().insert("x-request-id", val);
    }
    resp
}

/// Creates the root `http_request` tracing span that wraps the entire
/// request lifecycle.
///
/// Must be placed after [`request_id_middleware`] so the ID is available.
/// The `enduser.id` field is filled later by the identity-resolution layer;
/// `http.response.status_code` is recorded after the response is produced.
///
/// Incoming W3C `traceparent`/`tracestate`
/// headers are extracted and set as the parent context on the span, enabling
/// end-to-end distributed tracing.
pub async fn request_span_middleware(
    req: axum::http::Request<axum::body::Body>,
    next: middleware::Next,
) -> Response {
    let request_id = req
        .extensions()
        .get::<RequestId>()
        .map(|r| r.0.clone())
        .unwrap_or_default();

    let method = req.method().clone();
    let path = req.uri().path().to_string();

    // Extract W3C trace context from incoming headers for distributed tracing.
    let parent_cx = {
        let extractor = HeaderExtractor(req.headers());
        opentelemetry::global::get_text_map_propagator(|p| p.extract(&extractor))
    };

    // Collect request headers for OTel attributes.
    let header_attrs: Vec<(String, String)> = req
        .headers()
        .iter()
        .filter_map(|(name, value)| {
            let name_str = name.as_str();
            // Skip sensitive headers.
            if name_str == "authorization" || name_str == "cookie" || name_str == "set-cookie" {
                return None;
            }
            value
                .to_str()
                .ok()
                .map(|v| (format!("http.request.header.{name_str}"), v.to_string()))
        })
        .collect();

    let query = req.uri().query().unwrap_or("").to_string();

    let span = tracing::info_span!(
        "http_request",
        request_id = %request_id,
        "http.request.method" = %method,
        "url.path" = %path,
        "url.query" = %query,
        "enduser.id" = tracing::field::Empty,
        "http.response.status_code" = tracing::field::Empty,
        "otel.status_code" = tracing::field::Empty,
    );

    use tracing_opentelemetry::OpenTelemetrySpanExt;
    for (key, value) in header_attrs {
        span.set_attribute(key, value);
    }
    let _ = span.set_parent(parent_cx);

    async move {
        let response = next.run(req).await;
        let status = response.status().as_u16();
        let span = tracing::Span::current();
        span.record("http.response.status_code", status);
        if status >= 500 {
            span.record("otel.status_code", "ERROR");
        }
        response
    }
    .instrument(span)
    .await
}

/// Wrapper around axum's `HeaderMap` implementing the OpenTelemetry `Extractor`
/// trait for W3C trace-context propagation.
struct HeaderExtractor<'a>(&'a axum::http::HeaderMap);

impl opentelemetry::propagation::Extractor for HeaderExtractor<'_> {
    fn get(&self, key: &str) -> Option<&str> {
        self.0.get(key).and_then(|v| v.to_str().ok())
    }

    fn keys(&self) -> Vec<&str> {
        self.0.keys().map(|k| k.as_str()).collect()
    }
}

/// Dynamic body-limit middleware: reads `max_artifact_bytes` from settings on
/// each request. Returns 413 Payload Too Large if the declared `Content-Length`
/// exceeds the current limit, and wraps the body in a byte-counting limiter
/// that enforces the limit on actual consumed bytes (protecting against
/// chunked requests that omit Content-Length).
pub async fn dynamic_body_limit(
    State(state): State<AppState>,
    req: axum::http::Request<axum::body::Body>,
    next: middleware::Next,
) -> Response {
    let limit = state.settings.load().max_artifact_bytes;

    // Fast reject: if Content-Length is declared and exceeds the limit,
    // reject immediately without reading any body bytes.
    if let Some(content_length) = req
        .headers()
        .get(header::CONTENT_LENGTH)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.parse::<u64>().ok())
    {
        if content_length > limit {
            return (
                StatusCode::PAYLOAD_TOO_LARGE,
                format!(
                    "request body of {} bytes exceeds limit of {} bytes",
                    content_length, limit
                ),
            )
                .into_response();
        }
    }

    // Wrap the body in a byte-counting limiter so that even requests without
    // Content-Length (e.g. chunked transfer encoding) are bounded.
    let (parts, body) = req.into_parts();
    let limited = LimitedBody::new(body, limit);
    let req = axum::http::Request::from_parts(parts, axum::body::Body::new(limited));

    next.run(req).await
}

/// A body wrapper that enforces a byte limit on the actual data consumed.
///
/// Tracks bytes seen across `poll_frame()` calls. When the cumulative size
/// exceeds `remaining`, returns a "payload too large" error on the next poll.
struct LimitedBody {
    inner: axum::body::Body,
    remaining: u64,
}

impl LimitedBody {
    fn new(inner: axum::body::Body, limit: u64) -> Self {
        Self {
            inner,
            remaining: limit,
        }
    }
}

impl http_body::Body for LimitedBody {
    type Data = bytes::Bytes;
    type Error = axum::Error;

    fn poll_frame(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Option<Result<http_body::Frame<Self::Data>, Self::Error>>> {
        // SAFETY: LimitedBody is Unpin because both fields are Unpin.
        let this = self.get_mut();
        let inner = Pin::new(&mut this.inner);

        match inner.poll_frame(cx) {
            Poll::Pending => Poll::Pending,
            Poll::Ready(None) => Poll::Ready(None),
            Poll::Ready(Some(Err(e))) => Poll::Ready(Some(Err(e))),
            Poll::Ready(Some(Ok(frame))) => {
                if let Some(data) = frame.data_ref() {
                    let len = data.len() as u64;
                    if len > this.remaining {
                        return Poll::Ready(Some(Err(axum::Error::new(PayloadTooLarge))));
                    }
                    this.remaining -= len;
                }
                Poll::Ready(Some(Ok(frame)))
            }
        }
    }

    fn is_end_stream(&self) -> bool {
        self.inner.is_end_stream()
    }

    fn size_hint(&self) -> http_body::SizeHint {
        self.inner.size_hint()
    }
}

/// Error type returned when the streaming body exceeds the byte limit.
#[derive(Debug)]
struct PayloadTooLarge;

impl std::fmt::Display for PayloadTooLarge {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("request body exceeds size limit")
    }
}

impl std::error::Error for PayloadTooLarge {}

/// Dynamic CORS middleware: reads `cors` config from settings on each request.
///
/// Handles preflight (OPTIONS) requests by returning early with CORS headers,
/// and adds CORS response headers to normal requests. Placed outside the auth
/// layer so preflight requests work without credentials.
pub async fn dynamic_cors(
    State(state): State<AppState>,
    req: axum::http::Request<axum::body::Body>,
    next: middleware::Next,
) -> Response {
    let settings = state.settings.load();
    let cors_cfg = match settings.cors.as_ref() {
        Some(c) => c,
        None => return next.run(req).await,
    };

    let origin = req.headers().get(header::ORIGIN).cloned();

    // Only process requests that have an Origin header.
    let origin = match origin {
        Some(o) => o,
        None => return next.run(req).await,
    };

    // Check if origin is allowed.
    if !is_origin_allowed(cors_cfg, &origin) {
        return next.run(req).await;
    }

    let is_preflight = req.method() == Method::OPTIONS
        && req.headers().contains_key("access-control-request-method");

    if is_preflight {
        let mut resp = StatusCode::OK.into_response();
        add_cors_headers(&mut resp, cors_cfg, &origin);
        add_preflight_headers(&mut resp, cors_cfg);
        return resp;
    }

    let mut resp = next.run(req).await;
    add_cors_headers(&mut resp, cors_cfg, &origin);
    resp
}

fn is_origin_allowed(cfg: &CorsConfig, origin: &HeaderValue) -> bool {
    if cfg.allowed_origins.iter().any(|o| o == "*") {
        return true;
    }
    let origin_str = match origin.to_str() {
        Ok(s) => s,
        Err(_) => return false,
    };
    cfg.allowed_origins.iter().any(|o| o == origin_str)
}

fn add_cors_headers(resp: &mut Response, cfg: &CorsConfig, origin: &HeaderValue) {
    let headers = resp.headers_mut();
    if cfg.allowed_origins.iter().any(|o| o == "*") {
        headers.insert(
            header::ACCESS_CONTROL_ALLOW_ORIGIN,
            HeaderValue::from_static("*"),
        );
    } else {
        headers.insert(header::ACCESS_CONTROL_ALLOW_ORIGIN, origin.clone());
        // Vary: Origin when reflecting specific origin.
        headers.append(header::VARY, HeaderValue::from_static("Origin"));
    }
}

fn add_preflight_headers(resp: &mut Response, cfg: &CorsConfig) {
    let headers = resp.headers_mut();

    // Access-Control-Allow-Methods
    let methods = cfg.allowed_methods.join(", ");
    if let Ok(val) = methods.parse() {
        headers.insert(header::ACCESS_CONTROL_ALLOW_METHODS, val);
    }

    // Access-Control-Allow-Headers
    let hdrs = cfg.allowed_headers.join(", ");
    if let Ok(val) = hdrs.parse() {
        headers.insert(header::ACCESS_CONTROL_ALLOW_HEADERS, val);
    }

    // Access-Control-Max-Age
    let max_age = cfg.max_age_secs.to_string();
    if let Ok(val) = max_age.parse() {
        headers.insert(header::ACCESS_CONTROL_MAX_AGE, val);
    }
}

/// Dynamic rate-limit middleware: delegates to `DynamicRateLimiter` on each request.
pub async fn dynamic_rate_limit(
    State(state): State<AppState>,
    req: axum::http::Request<axum::body::Body>,
    next: middleware::Next,
) -> Response {
    if let Err(resp) = state.rate_limiter.check(&req) {
        return resp.into_response();
    }
    next.run(req).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_origin_allowed_wildcard() {
        let cfg = CorsConfig {
            allowed_origins: vec!["*".to_string()],
            allowed_methods: vec![],
            allowed_headers: vec![],
            max_age_secs: 0,
        };
        let origin = HeaderValue::from_static("http://anything.example.com");
        assert!(is_origin_allowed(&cfg, &origin));
    }

    #[test]
    fn test_is_origin_allowed_specific_match() {
        let cfg = CorsConfig {
            allowed_origins: vec!["http://localhost:3000".to_string()],
            allowed_methods: vec![],
            allowed_headers: vec![],
            max_age_secs: 0,
        };
        let origin = HeaderValue::from_static("http://localhost:3000");
        assert!(is_origin_allowed(&cfg, &origin));
    }

    #[test]
    fn test_is_origin_allowed_no_match() {
        let cfg = CorsConfig {
            allowed_origins: vec!["http://localhost:3000".to_string()],
            allowed_methods: vec![],
            allowed_headers: vec![],
            max_age_secs: 0,
        };
        let origin = HeaderValue::from_static("http://evil.com");
        assert!(!is_origin_allowed(&cfg, &origin));
    }
}
